
use customer_behaviour_analysis;
SELECT * 
FROM customer_behaviour_analysis.customer_shopping;



-- 1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) from customer_shopping
group by gender;


-- 2. Which customers used a discount but still spent more than the average purchase amount?

select customer_id, purchase_amount as avg_purchase_amount
from customer_shopping
where discount_applied = "Yes" and purchase_amount >= (select avg(purchase_amount)from customer_shopping);



-- 3. Which are the top 5 products with highest average  review rating?

select 
item_purchased,
round(avg(review_rating),2) as "Average_review_rating" 
from customer_shopping
group by item_purchased 
order by avg(review_rating) desc
limit 5;


-- 4. Compare the average purchase_amounts between Standard and express shipping

select shipping_type,
round(avg(purchase_Amount),2) as "average purchase_amount"
from customer_shopping
where shipping_type in ( 'Standard' , 'Express')
group by shipping_type ;



-- 5. Do subscribed customers are more?Compare the average spend  and total revenue  between subscribers and non-subscribers?

select 
subscription_status, count(customer_id) as Subscription_status,
round(sum(purchase_amount),2) as total_revenue,round(avg(purchase_amount),2) as total_spend
from customer_shopping
where subscription_status in('Yes','No')
group by subscription_status
order by total_revenue, total_spend asc;

-- 6. Which 5 products have the highest percentage of purchases with discount applied?

select item_purchased, round(sum(discount_applied = 'Yes')*100/count(*),2) as discount_percentage
from customer_shopping
group by item_purchased
order by discount_percentage desc
limit 5;

-- 7. Segment customers  into new , returning  and loyal  based on their  total number  of previous purchases, 
-- and show the count of each segment

select distinct(count(item_purchased))
from customer_shopping;

-----------          both the count of item_purchased and purchase_amount has same - 3600           ----------

select 
case 
when previous_purchases = 1 then "New"
when previous_purchases between 2 and 10  then "Returning"
else "Loyal"
end as customer_segment,
count(*) as total
from customer_shopping
group by customer_segment;



-- 8. What is top 3 most purchased products within each category?

select category, item_purchased,
count(*) as total_products_per_category
from customer_shopping
group by category , item_purchased
order by category desc
limit 3;



-- 9.  Are customers who are repeat buyers(more than 5 previous purchases) are also likely to subscribe?

select * from customer_shopping;

select subscription_status,
count(customer_id) as customer_repeat_buyers
from customer_shopping
where previous_purchases >5
group by subscription_status;


-- 10.  What is the revenue contribution of each age group?

select age_group,
sum(purchase_amount) as Revenue_Contribution
from customer_shopping
group by age_group
order by Revenue_Contribution desc;












